### PR TITLE
refine logging

### PR DESCRIPTION
**Pull request by rkaminsk**

### CODE REVIEW

**Comment by rkaminsk** [comment]
@susuhahnml and @MaxOstrowski: what about the following?

**Comment by MaxOstrowski** [comment]
@rkaminsk @susuhahnml @sthiele maybe the review got lost as it seems it got added after the issue was closed. But the remarks seem to be lost now.
As the issue was also closed (and I miss the rights to reopen it) maybe I can get your quick opinion about my questions here ?

**Comment by rkaminsk** [comment]
Do you mean the questions in #25? I tried to address them here. If you think that there should be further changes, you could open a new PR. The goal was to get some color in for simple command line applications (because this is not completely trivial) and not to interfere at all in the case of libraries. The logger can now be used exactly as you suggest in this setting.

**Comment by MaxOstrowski** [comment]
No. I'm not sure if this is visible to you, might had some problems with my github App on Android. There was a review to the PR with some simple questions:

```
NOTSET = logging.NOTSET
...
```
Why do we redefine these values ?

```
def get_logger(name: str) -> logging.Logger:
```
Why do we redefine this function ?

```
# nocoverage
```
We should add some tests.

I will just propose a PR this week and we can continue the discussion there.

**Comment by rkaminsk** [comment]
Somehow, I did not even get an email for this.

> No. I'm not sure if this is visible to you, might had some problems with my github App on Android. There was a review to the PR with some simple questions:
> 
> ```
> NOTSET = logging.NOTSET
> ...
> ```
> 
> Why do we redefine these values ?

To avoid having to import two modules. The idea was to expose a minimal interface to do logging. For my use cases in the past it was enough to have one function/object to log plus the levels. This might turn out to be insufficient for complex cases.

> ```
> def get_logger(name: str) -> logging.Logger:
> ```

Same as above plus the getLogger function from python's default module is old and ugly. It does not even follow python's recommended naming scheme.

> Why do we redefine this function ?
> 
> ```
> # nocoverage
> ```
> We should add some tests.

This is difficult to test because (I think that) by design, the logger setup should only run once and then cannot be changed.

If you don't like the reexporting, you can also just import the configure function and use the logging module directly. Or maybe you even want to extend the module to add more functions to do logging as required by your application.

**Pull request merged**
