### PR TITLE
Shorten CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by sthiele**
As discussed in Issue #33 a proposal for a much condensed CONTRIBUTING.md

### CODE REVIEW

**Comment by rkaminsk** [comment]
Maybe we should have a vote which one to take? I personally don't care much.

Put a :t-rex: for the old one and a :cockroach: for the new one.

**Comment by javier-romero** [comment]
Hi, I have no experience at all on this so I won't vote, but I feel that:
* in the template it is better to have the reduced version, since the other is overkill to me
* it would still be good to have a link in the reduced version to the extended version (that should be somewhere accessible) since it can be useful to some people

**Comment by rkaminsk** [comment]
> Hi, I have no experience at all on this so I won't vote, but I feel that:
> 
>     * in the template it is better to have the reduced version, since the other is overkill to me

I prefer short readmes. I think that for a contributing guide it is not as important to be concise. 

Things to consider:
- An experienced programmer is only interested in whether PRs are accepted and what form they should have. The short version tells him that PRs are accepted.
- An inexperienced programmer does not get much information.

>     * it would still be good to have a link in the reduced version to the extended version (that should be somewhere accessible) since it can be useful to some people

So far we do not have a general contributing guide for the organization and I am not sure we should have one.

**Review by tortinator — APPROVED** [review]

**Comment by sthiele** [comment]
@rkaminsk How about this?

**Comment by rkaminsk** [comment]
Maybe we should also try to find a markdown auto formatter. I like to read markdown in my text editor.

**Comment by rkaminsk** [comment]
I found the formatters:
- https://github.com/executablebooks/mdformat
- https://prettier.io/

And these linters:
- https://github.com/jackdewinter/pymarkdown
- https://github.com/markdownlint/markdownlint
- https://github.com/igorshubovych/markdownlint-cli

All of them bring precommit hooks. mdformat seems nice and simple.

**Comment by sthiele** [comment]
> Maybe we should also try to find a markdown auto formatter. I like to read markdown in my text editor.

I use https://github.com/DavidAnson/vscode-markdownlint.
It does not restrict line width ... my editor can do dynamic line wrapping :stuck_out_tongue:

**Comment by rkaminsk** [comment]
> > Maybe we should also try to find a markdown auto formatter. I like to read markdown in my text editor.
> 
> I use https://github.com/DavidAnson/vscode-markdownlint. It does not restrict line width ... my editor can do dynamic line wrapping 😛

Mine too. I just added mdformat and I like what it does. :smile:

**Pull request merged**
